config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'

  controller :owners do
    devise_for :owners, controllers: {
      sessions: 'owners/sessions',
      passwords: 'owners/passwords',
      registrations: 'owners/registrations'
    }
    devise_scope :owner do
      post 'owners/guest_sign_in', to: 'owners/sessions#guest_sign_in'
    end
    resources :owners
  end

  controller :users do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
    resources :users, only: [:show] do
      collection do
        get 'review'
      end
    end
  end

  resources :shops do
    resources :reviews
  end

  resources :reviews do
    resources :comments
  end

  resources :relationships, only: %i[create destroy]
  resources :blacklists

  controller :guides do
    get :review_poricy, to: 'guides#review_poricy'
    get :guideline, to: 'guidse#guideline'
  end
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true
  VALID_TIME_REGEX = /\A\d{2}:\d{2}$|^\d{1}:\d{2}\z/
  validates :start_dt, presence: true, format: { with: VALID_TIME_REGEX }
  validates :end_dt, presence: true, format: { with: VALID_TIME_REGEX }
  validates :detail, length: { maximum: 500 }
  VALID_TEL_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :contact_detail, format: { with: VALID_TEL_REGEX }
  validates :url, allow_blank: true, format: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/
  belongs_to :owner
  has_many :reviews, dependent: :destroy
  has_many :review_users, through: :reviews, source: :user
  mount_uploader :image, ImageUploader
  has_many :blacklists, dependent: :destroy
  has_many :blacklist_users, through: :blacklists, source: :user
  attr_accessor :average, :review_count

  def review_score_percentage
    if reviews
      reviews.average(:score).to_f * 100 / 5
    else
      0.0
    end
  end

  def review_score_average
    if reviews
      reviews.average(:score).to_f.round(1)
    else
      0.0
    end
  end

  def blacklist_user(user)
    blacklists.find_by(user_id: user).present?
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update destroy]
  before_action :owner?, only: %i[new ceate edit update]

  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).page(params[:page]).per(5)
    # 評価順で並べるばあい
    if params[:sort_top_review]
      @shops = Shop.all.each do |shop|
        shop.average = shop.review_score_average
      end
      @shops = @shops.sort_by { |shop| shop.average }.reverse
      @shops = Kaminari.paginate_array(@shops[0..9]).page(params[:page])
    # クチコミ数の多い順
  elsif params[:review_count]
      @shops = Shop.all.each do |shop|
        shop.review_count = shop.reviews.count
      end
      @shops = @shops.sort_by { |shop| shop.review_count }.reverse
      @shops = Kaminari.paginate_array(@shops).page(params[:page]).per(5)
    end
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.owner_id = current_owner.id
    if @shop.save
      redirect_to shops_path, notice: '新規登録しました'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @shop.update(shop_params)
      redirect_to owner_path(@shop.owner_id), notice: '店舗の編集をしました'
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to owner_path(@shop.owner_id), notice: '店舗を削除しました'
  end

  private

  def shop_params
    params.require(:shop).permit(
      :name,
      :brand,
      :address,
      :start_dt,
      :end_dt,
      :detail,
      :url,
      :contact_detail,
      :image,
      :image_cache
    )
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def owner?
    redirect_to shops_path, notice: 'エラー' unless authenticate_owner!
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def default_img(image)
    image.presence || 'default.jpg'
  end
  # def blacklist_user(review)
  #   @shop = Shop.find(review.shop_id)
  #   @user = review.user_id
  #   @shop.blacklists.find_by(user_id:@user).present?
  # end
end

app/views/shops/_form.html.erb
<div class = "container">
  <div class="row">
    <div class="col-md-2" ></div>
    <div class="col-md-8" >
      <div class="card" id="new_shop_card">
        <%= form_with(model: @shop, local: true) do |form| %>
        <% if @shop.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% @shop.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="new-shop-field">
          <%= form.label :name, class:"required" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :brand %>
          <%= form.text_field :brand, class: "form-control" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :address, class:"required" %>
          <%= form.text_area :address, class: "form-control" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :start_dt, class:"required" %>
          <%= form.text_field :start_dt , class: "form-control", placeholder: "例:9:00 半角数字で入力してください" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :end_dt, class:"required" %>
          <%= form.text_field :end_dt, class: "form-control", placeholder: "例:20:00 半角数字で入力してください" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :detail %>
          <%= form.text_area :detail, class: "form-control" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :url %>
          <%= form.text_area :url, class: "form-control" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :contact_detail, class:"required" %>
          <%= form.text_field :contact_detail, placeholder: "ハイフンは入れずに半角数字で入力してください", class: "form-control" %>
        </div>

        <div class="new-shop-field">
          <%= form.label :image %>
          <%= image_tag(@shop.image.url) if @shop.image && @shop.image.url %>
          <%= form.file_field :image %>
          <%= form.hidden_field :image_cache %>
        </div>

        <br>
        <div class="actions">
          <%= form.submit %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-2" ></div>
  </div>
</div>
<%= link_to '店一覧へ', shops_path %>

app/views/shops/edit.html.erb
<br><h2>登録店舗編集</h2>
<%= render 'form' %>

app/views/shops/index.html.erb
<!-- 検索body -->
<section id= "top" class="shop-index-top">
  <h4 id="find-shop-sub">アパレル店のクチコミができるアプリ</h4>
  <h1 id="find-shop">APPALOG</h1>

  <div class = "container" >
    <%= search_form_for @q do |f| %>
    <%= f.search_field :name_or_brand_or_address_cont, class: "form-control", placeholder: "店舗名 ブランド 住所検索", id:"search-box" %>
    <%= button_tag type: 'submit',class: "btn btn-danger" do %>
    <i class="fas fa-search"></i> 検索
    <% end %>
    <% end %>
  </div>
</section>

<!-- body -->
<div class = "container">
  <div class = "container-fluid">
    <div class = "row">
      <!-- サイドバー -->
      <div class = "col-md-2">
        <aside class="side-menu">
          <nav>
            <br>
            <!-- <%= link_to "クチコミ評価が良い店Top10", shops_path(sort_top_review: "true"), class:"btn btn-outline-primary" %><br> -->
            <div class="btn-group">
              <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                並べ替え
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item"><%= link_to "星評価の高い店Top10", shops_path(sort_top_review: "true") %></a>
                <!-- <a class="dropdown-item" href="#">クチコミ数の少ない順</a> -->
                <a class="dropdown-item"><%= link_to "クチコミ数が多い順", shops_path(review_count: "true") %></a>
              </div>
            </div>
          </nav>
        </aside>
      </div>

      <!-- shops情報 -->
      <div class = "col-md-10">
        <% if @shops.empty? %>
        <br>
        <p>検索条件と一致する結果が見つかりません</p>
        <% end %>
        <% @shops.each do |shop| %><p>
          <div class = "row">
            <div class = "review-post col-md-12">
              <p>店舗名:<%= link_to shop.name, shop_path(shop.id) %></p>
              <p><%= shop.address %></p>
              <p>営業時間:<%= shop.start_dt%></p>
              <p>閉店時間:<%= shop.end_dt%></p>
              <div class="content average-score">
                <div class="star-rating" style='margin-left: auto; margin-right: auto;'>
                  <div class="star-rating-front" style="width:<%= shop.review_score_percentage %>%">★★★★★</div>
                  <div class="star-rating-back">★★★★★</div>
                </div>
                <div class="average-score-display ml-3 pt-2">
                  <%= shop.review_score_average %>点
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <!-- kaminari -->
          <div class = "paginate col-8 offset-2">
            <%= paginate @shops %>
          </div>
          <!-- shos情報閉じタグ -->
        </div>
        <!-- row閉じタグ -->
      </div>
      <!-- container_f閉じタグ -->
    </div>
    <!-- container閉じタグ -->
  </div>

  <footer class="footer">
    <div class="footermenubox clearfix">
      <ul class="footermenust">
        <!-- <%= link_to 'アパログの使い方', review_poricy_path%>< -->
        <li>アパログの使い方</li>
        <li>クチコミガイドライン</li>
        <li>お問い合わせ</li>
      </ul>
    </div>
    <div class="footer-logo">
      <p>APPALOG</p>
    </div>
    <div class="copylight">
      <p>© 2021 APPALOG</p>
    </div>
  </footer>

app/views/shops/new.html.erb
<br><h2>新規店舗登録</h2>
<%= render 'form' %>

app/views/shops/show.html.erb
<div class='container-fluid' id='show-container'>
  <p>
    <%= image_tag default_img(@shop.image.url) %>
  </p>
  <h1><%= "#{@shop.brand}" %></h1>
  <!-- star -->
  <div class="star-rating" style='margin-left: auto; margin-right: auto;'>
    <div class="star-rating-front" style="width:<%= @shop.review_score_percentage %>%">★★★★★</div>
    <div class="star-rating-back">★★★★★</div>
  </div><br>
  <div class="review-score-display">
    <p>評価:<%= @shop.review_score_average %>点 / クチコミ数<%= @shop.reviews.count %>件</p>
  </div>
<!-- shop_details -->
  <p>店舗名:　<%= @shop.name %></p>
  <p>住所: <%= @shop.address %></p>
  <p>営業時間:<%= @shop.start_dt%></p>
  <p>閉店時間:<%= @shop.end_dt%></p>
  <p>詳細:<%= @shop.detail %></p>
  <p>url:<%= @shop.url %></p>
  <p>電話番号:<%= @shop.contact_detail %></p>

  <%= link_to 'クチコミ', shop_reviews_path(shop_id: @shop.id), class:"btn btn-primary" %><br></br>
  <%= link_to '店一覧へ', shops_path %>
</div>