config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'

  controller :owners do
    devise_for :owners, controllers: {
      sessions: 'owners/sessions',
      passwords: 'owners/passwords',
      registrations: 'owners/registrations'
    }
    devise_scope :owner do
      post 'owners/guest_sign_in', to: 'owners/sessions#guest_sign_in'
    end
    resources :owners
  end

  controller :users do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
    resources :users, only: [:show] do
      collection do
        get 'review'
      end
    end
  end

  resources :shops do
    resources :reviews
  end

  resources :reviews do
    resources :comments
  end

  resources :relationships, only: %i[create destroy]
  resources :blacklists

  controller :guides do
    get :review_poricy, to: 'guides#review_poricy'
    get :guideline, to: 'guidse#guideline'
  end
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_session.html.erb
<br>
<div class = "container">
  <div class="row col-md-6 col-md-offset-3 col-xs-10">
    <div class = "card auth-card">
      <h4><%= t('devise.sessions.new.sign_in') %></h4><br>

      <%= link_to 'ゲストログイン（ユーザー閲覧用）', users_guest_sign_in_path, method: :post, class:"btn btn-warning"%><br>
      <%= link_to 'ゲストログイン（店主閲覧用）', owners_guest_sign_in_path, method: :post, class:"btn btn-success" %>

      <br><hr>

      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <br/>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder:"メールアドレス" %>
      </div>

      <div class="field">
        <br/>
        <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder:"パスワード" %>
      </div>

      <!-- <% if devise_mapping.rememberable? %>
      <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
      </div>
      <% end %> -->

      <div class="actions">
        <%= f.submit t('devise.sessions.new.sign_in'), class: "btn btn-info btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>