config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'

  controller :owners do
    devise_for :owners, controllers: {
      sessions: 'owners/sessions',
      passwords: 'owners/passwords',
      registrations: 'owners/registrations'
    }
    devise_scope :owner do
      post 'owners/guest_sign_in', to: 'owners/sessions#guest_sign_in'
    end
    resources :owners
  end

  controller :users do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
    resources :users, only: [:show] do
      collection do
        get 'review'
      end
    end
  end

  resources :shops do
    resources :reviews
  end

  resources :reviews do
    resources :comments
  end

  resources :relationships, only: %i[create destroy]
  resources :blacklists

  controller :guides do
    get :review_poricy, to: 'guides#review_poricy'
    get :guideline, to: 'guidse#guideline'
  end
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_review, only: %i[show edit update destroy]
  before_action :set_shop, only: %i[show index destroy]
  before_action :block_blacklist_user, only: %i[new edit update create]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @review.shop_id = params[:shop_id]
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.shop_id = params[:shop_id]
    if @review.save
      redirect_to shop_reviews_path, notice: 'クチコミ投稿しました！'
    else
      render :new
    end
  end

  def show
    @comments = @review.comments
    @comment = @review.comments.build
  end

  def edit
    @review.shop_id = params[:shop_id]
  end

  def update
    if @review.update(review_params)
      redirect_to shop_reviews_path, notice: 'クチコミを編集しました！'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to shop_reviews_path, notice: 'クチコミを削除しました！'
  end

  private

  def review_params
    params.require(:review).permit(:content, :score)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  def block_blacklist_user
    redirect_to shop_reviews_path, notice: 'こちらのショップには投稿できません！' if set_shop.blacklist_user(current_user)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def create_or_update
    if action_name == 'create' || action_name == 'new'
      shop_reviews_path
    elsif action_name == 'edit'
      shop_review_path
    end
  end
end

app/views/reviews/_form.html.erb
<%= form_with(model: @review, url: create_or_update, local: true) do |form| %>

<% if @review.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= form.label :content %><br>
    <%= form.text_area :content, style:"width:500px; resize: none; height:200px;"%>
  </div>

  <div class="evaluation">
    <%= form.radio_button :score, 5, id:"star5"%><label for="star5">★</label>
    <%= form.radio_button :score, 4, id:"star4"%><label for="star4">★</label>
    <%= form.radio_button :score, 3, id:"star3"%><label for="star3">★</label>
    <%= form.radio_button :score, 2, id:"star2"%><label for="star2">★</label>
    <%= form.radio_button :score, 1, id:"star1"%><label for="star1">★</label>
  </div>

  <div class="actions">
    <%= form.submit "投稿する" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h2>クチコミの編集</h2>
<%= render "form" %>

app/views/reviews/index.html.erb
<h2><%= link_to @shop.name, shop_path(@shop)%>のクチコミ一覧 </h2>
<% if current_user %>
  <%= link_to 'クチコミする', new_shop_review_path, class: 'btn btn-primary' %>
<% end %>
<div class = "container">
  <% @shop.reviews.each do |review| %><p>
    <div class = "row">
      <div class = "review-post col-8 offset-2">
        <% if user_signed_in? %>
        <p>投稿者:<%= link_to review.user.name, user_path(review.user.id) %></p>
        <% unless current_user.id == review.user.id %>
        <%= render 'users/follow_form', user: review.user %>
        <% end %>
        <% else %>
        <p>投稿者: <%= review.user.name %></p>
        <% end %>
        <p><%= review.content%></p>
        <!-- .truncate(50, separator: /\s/) もっとみるボタン実装後追加 -->

        <div class="content review-score">
          <div class="star-rating" style='margin-left: auto; margin-right: auto;'>
            <div class="star-rating-front" style="width:<%= review.score_percentage %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
          </div><br>
          <div class="review-score-display">
            評価：<%= review.score %>点
          </div>
        </div>

        <p>投稿時間:<%= l review.created_at, format: :long %></p>
        <form>
          <% if user_signed_in? %>
            <% if current_user.id == review.user.id %>
              <%= link_to '編集する', edit_shop_review_path(@shop.id,review.id),class:"btn btn-outline-primary btn-sm"%>
              <%= link_to '削除する', shop_review_path(@shop.id,review.id), method: :delete, data: { confirm: '本当に編集していいですか？' },class:"btn btn-outline-primary btn-sm" %>
            <% end %>
          <% end %>
          <% if current_owner == @shop.owner || current_user == review.user %>
            <%= link_to '詳細表示', shop_review_path(@shop.id,review.id),class:"btn btn-outline-primary btn-sm" %>
          <% end %>
        </form>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2>新規クチコミ投稿</h2>
<%= render "form" %>

app/views/reviews/show.html.erb
<div class='container' id='show-container'>
  <h2>詳細画面</h2>
  <div class="blacklist-button">
    <table>
      <tr>
        <% if owner_signed_in? && current_owner.id == @shop.owner.id %>
          <% if @shop.blacklist_user(@review.user) %>
            <td><%= button_to "#{@review.user.name}さんをブラックリストから解除", blacklist_path(id:@review), method: :delete,  data: { confirm: "#{@review.user.name}さんをブラックリストから解除しますか？" }, class:"btn btn-dark"%></td>
          <% else %>
            <td>  <%= button_to "#{@review.user.name}さんをブラックリストに入れる", blacklists_path(id:@review), method: :post, data: { confirm: "#{@review.user.name}さんをブラックリストに入れますか？" }, class:"btn btn-outline-dark" %></td>
          <% end %>
          <!-- <td><input class="hatena_button" type="button" name="" value="？">
            <span class="help_message"></span>
          </td> -->
          <td>
            <button type="button" class="btn btn-info" id="tooltip-branck" data-toggle="tooltip" data-placement="right" title="ブラックリストに入れたユーザーはこの店に対してクチコミができなくなります">
              ?
            </button>
          </td>
        <% end %>
      </tr>
    </table>
  </div>

  <% if user_signed_in? %>
    投稿者: <%= link_to @review.user.name, user_path(@review.user.id) %>
    <% unless current_user.id == @review.user.id %>
      <%= render 'users/follow_form', user: @review.user %>
    <% end %>
  <% else %>
    <p>投稿者: <%= @review.user.name %></p>
  <% end %>
  <p>内容: <%= @review.content %></p>

  <% if owner_signed_in? && current_owner.id == @shop.owner.id %>
    <%= render partial: 'comments/form', locals: { comment: @comment, review: @review } %>
  <% end %>

  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, review: @review } %>
  </div></br>

  <%= link_to 'クチコミ一覧へ', shop_reviews_path %>
</div>

<script>
  // $('.hatena_button').on('click', function(){
  //   if($('.help_message').text() === ""){
  //     $('.help_message').text("ブラックリストに入れたユーザーはこの店に対してクチコミができなくなります").fadeIn(500).css('display', 'inline');
  //   } else {
  //     $('.help_message').text("").css('display', 'none');
  //   }
  // })

  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>