config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'

  controller :owners do
    devise_for :owners, controllers: {
      sessions: 'owners/sessions',
      passwords: 'owners/passwords',
      registrations: 'owners/registrations'
    }
    devise_scope :owner do
      post 'owners/guest_sign_in', to: 'owners/sessions#guest_sign_in'
    end
    resources :owners
  end

  controller :users do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
    resources :users, only: [:show] do
      collection do
        get 'review'
      end
    end
  end

  resources :shops do
    resources :reviews
  end

  resources :reviews do
    resources :comments
  end

  resources :relationships, only: %i[create destroy]
  resources :blacklists

  controller :guides do
    get :review_poricy, to: 'guides#review_poricy'
    get :guideline, to: 'guidse#guideline'
  end
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppalogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <!-- popper -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <!-- Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <!-- font awesome -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark">
      <div class="container">
        <a><%= link_to "APPALOG", root_path, class:"navbar-brand" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

          <ul class="navbar-nav mr-auto">　
            <% if current_owner %>
            <li><%= link_to '店舗登録', new_shop_path, class:"nav-link" %></li>
            <li><%= link_to '登録した店舗', owner_path(current_owner.id), class:"nav-link" %></li>
            <% end %>
          </ul>

          <ul class="navbar-nav">
            <a><%= link_to "ホーム", root_path, class:"nav-link" %></a>
            <% unless current_owner %>
              <% if user_signed_in? %>
              <li>
                <a><%= link_to "マイページ", user_path(current_user.id), class:"nav-link" %></a>
              </li>
              <li>
                <a><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link" %></a>
              </li>
              <% else %>
              <li>
                <a><%= link_to "新規登録", new_user_registration_path, class:"nav-link" %></a>
              </li>
              <li>
                <a><%= link_to "ログイン", new_user_session_path, class:"nav-link" %></a>
              </li>
              <% end %>
            <% end %>

            <% if current_owner %>
              <% if owner_signed_in? %>
              <li>
                <a><%= link_to "ログアウト", destroy_owner_session_path, method: :delete, class:"nav-link" %></a>
              </li>
              <% else %>
              <li>
                <a><%= link_to "新規登録", new_owner_registration_path, class:"nav-link" %></a>
              </li>
              <li>
                <a><%= link_to "ログイン", new_owner_session_path, class:"nav-link" %></a>
              </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>

</html>